### PR TITLE
Reface with a new logo and new theme

### PR DESCRIPTION
**Pull request by syleeeee**
Finally, this pull request applies the new logo for OpenZipkin. #132  

Here is the preview. 
preview

### CODE REVIEW

**Comment by syleeeee** [comment]
> (nit: we probably don't want to commit .DS_Store files)

Oops, sorry. Removed it.

**Comment by devinsba** [comment]
@basvanbeek voiced a concern in gitter that I'd like to echo here. Do we intend to use `OpenZipkin` on the logo/names of things? Or should we instead use `Zipkin`?

**Comment by adriancole** [comment]
good point about openzipkin vs zipkin. since there's no non-open zipkin (except sometimes the bait and switch ads), maybe we should keep it simple and use "zipkin" in all places except discussing the community itself. If the org named "zipkin" was available, twitter/zipkin would have become simply zipkin/zipkin heh

**Comment by shakuzen** [comment]
My thoughts: I would prefer to use just Zipkin everywhere except when referring to the org.

**Comment by syleeeee** [comment]
I think these caused ambiguous parts, 
-  I haven't changed anything but logo and theme color. 
- But If we agree to use 'OpenZipkin' when we call the community, then I think I should change some words 'Zipkin' to 'OpenZipkin'.
    - Such as, `Zipkin Community` to `OpenZipkin Community` on the side bar. 
    - But leave the main page which describes [Zipkin](https://github.com/openzipkin/zipkin) itself. 

So how about this? 
If someone wants to use the logo with Zipkin, then just use the icon without the text. And the text in full logotype was created with the font [Noto Sans](https://www.google.cn/get/noto/), anyone can put 'Zipkin' next to the icon.  

But I'd like to let you know that we can change the whole logo `OpenZipkin` to `Zipkin`. 
(Personally, I prefer to maintain `OpenZipkin` for the community)

Any feedbacks are always welcomed.

**Comment by jcchavezs** [comment]
I would prefer zipkin as it is more consistent with what we have now in the ecosystem and is less confusing because not having `open`. I think it still make sense to call the organization as `openzipkin` because as far as I understand it comes from the fact that zipkin started at Twitter and when moved to open source, `openzipkin` was created for that purpose.

**Comment by adriancole** [comment]
I agree with saying OpenZipkin in text we talk about community. I do the
same in slides.

I am a little concerned about indicating a usage policy of the logo because
vendors use it to sell things that have nothing to do with it. or use our
logo to sell jaeger. I dont know the best way to handle this but maybe
policy can be a different PR?

meanwhile good to have 2 variants one for Zipkin and another for OpenZipkin
perhaps with simplified text that Zipkin is for open source tools
compatible with Zipkin formats and OpenZipkin is exclusively used to
describe the team that shepard the zipkin ecosystem?

at any rate again we can do in separate change policy and naming of logo vs
logo itself.

other opinions?

**Comment by adriancole** [comment]
hi @syleeeee I know you are busy. wondering if we can get a plain Zipkin logo sometime soon. I think the OpenZipkin variant will be used maybe 1% of the time. As soon as we have a Zipkin one, we can update the server which is where people will see possibly even more than the website.

**Comment by syleeeee** [comment]
@adriancole Hi, 
Sorry for the late response. (having hectic days with a business trip ✈️ ) 
Discussed with the designer in LINE, she expects the work going back to `Zipkin` will be done in the first week of September. 
So let me update these as soon as getting the `Zipkin` logo file.

**Comment by syleeeee** [comment]
@adriancole @shakuzen @jcchavezs @zeagord 
Sorry for the late response. 
How about now? 
image

**Comment by adriancole** [comment]
looks good. just some dead links like https://github.com/openzipkin/openzipkin.github.io/tree/master/public/img/logo_svg

**Comment by adriancole** [comment]
Great to see this landed! Thanks so much!

**Comment by syleeeee** [comment]
Whoooooo 🚀 
Thank everyone for the vote!

**Comment by adriancole** [comment]
Added issue to update lens https://github.com/openzipkin/zipkin/issues/2806

**Pull request merged**
