### PR TITLE
add page with logos and instructions to print stickers

### PR DESCRIPTION
**Pull request by ahus1**
This adds a new page to the Zipkin homepage with links to SVG logos and instructions to print stickers.

### CODE REVIEW

**Comment by ahus1** [comment]
I used jekyll serve. Please see the attached screenshot. Changes highlighted in red. 

I went with the default menu ordering. 

I've considered a logo preview instead of a link - but finally decided against it: Providing it as a link with a proper name makes it easier to decide and use right-click-download. A (left) click on the link provides a full-window preview of the logo.

zipkin_logo_site

**Comment by adriancole** [comment]
Thanks this helps!

Only thing that jumps out at me is that this doesn't fit with the rest of
the categories. For example, most things are technical and logos feels a
bit random between instructions on how to instrument and transports :)

maybe separate with a blank line, then make this page called "community"?
This could be the first section of community.md or something

**Comment by ahus1** [comment]
The ordering is random as everything below existing documentation doesn't have an explicit order ("weight" in the file).

I'm not sure if someone looking for logos would click on "community". And for now there is no other community content than the logos. And wouldn't "existing instrumentations" count as community as well?

Therefore I suggest: Add explicit ordering for all pages that keeps the original order and places the new page "Logos" last.

Once more content is added it could be refactored to a new structure.

**Comment by adriancole** [comment]
We dont get people asking about logos often and I dont think it warrants
being on the front page as its own link. Are you aware of other projects
who have a link to how to print stickers on their nav bar?

**Comment by adriancole** [comment]
so I guess what's the issue is that we are missing a community page, and you'd prefer that present before starting one. I was going to work on other things today, but I'll start on this so that your change can get merged faster

**Comment by adriancole** [comment]
let's rebase this once https://github.com/openzipkin/openzipkin.github.io/pull/92 is merged

**Comment by adriancole** [comment]
lemme know if you need a hand with this. I'll be offline from tomorrow for several days, though others can help get this merged.

**Comment by ahus1** [comment]
@adriancole - thanks, I now see what you had in mind with "community". 

Just that we are on the same page: the thing to do would be to put the contents of the logo.md at the end of community.md

**Comment by ahus1** [comment]
I've update the PR and integrated the logo information into the community.md page (at the end). 

@adriancole  / @jcchavezs  / @shakuzen Ready for review. Screenshot below.

zipkin_logo_site

**Pull request merged**
