### PR TITLE
Move existing documentation here, using Jekyll

### PR DESCRIPTION
**Pull request by abesto**
Taking some ideas from the way http://opentracing.io/ is built. Click: http://abesto.github.io/openzipkin.github.io/

This is in preparation of improving documentation on design decisions / internals, and implementation details, with the thinly veiled goal of replacing the current http://zipkin.io/.

screenshot 2016-02-28 11 12 10

### CODE REVIEW

**Comment by abesto** [comment]
@rtyler @adriancole

**Comment by abesto** [comment]
There are some problems with `baseurl`, working on figuring out a nice solution right now

**Comment by eirslett** [comment]
Sweet!!!! :+1:

**Comment by adriancole** [comment]
:+1:

**Comment by adriancole** [comment]
thanks so much for this breath of life into the doc site

**Pull request merged**
