### PR TITLE
revert: zipkin-api is being published automatically so no more submodules

### PR DESCRIPTION
**Pull request by jcchavezs**
After a chat with @abesto for the sake of less maintenance complexity wewill keep the old flow (zipkin-api publishing itself) so we don't need the submodule approach anymore.

Ping @adriancole

### CODE REVIEW

**Comment by adriancole** [comment]
cool.. maybe remind how https://zipkin.io/zipkin-api/#/default ends up mounted, if not this way

**Comment by jcchavezs** [comment]
It is being published directly from `zipkin-api` repository. I need to fix
that publishing as well.

José Carlos Chávez


man. 26. aug. 2019 kl. 02:11 skrev Adrian Cole <notifications@github.com>:

**Comment by adriancole** [comment]
I mean the URL forwarding of https://zipkin.io/zipkin-api/#/default to
whatever is the result of that publishing.. or if you mean that publishing
pushed content to this repo?

sorry really I just forget how this works.

**Comment by jcchavezs** [comment]
So the current status is that https://zipkin.io/zipkin-api/ is published by https://github.com/openzipkin/zipkin-api automatically (configured in the settings of https://github.com/openzipkin/zipkin-api) so whatever is under `/zipkin-api` is not controlled by this repo that is why we don't need the submodule thing anymore. Although this is counter intuitive, @abesto and I agree this is easier to maintain. I think i could drop a line about this in the readme.

**Comment by adriancole** [comment]
sg about a "how this works" section

**Comment by adriancole** [comment]
merging, would appreciate a "how this works" after the fact

**Comment by adriancole** [comment]
hmm the api listed is super old https://zipkin.io/zipkin-api/zipkin2-api.yaml doesnt even have autocomplete endpoints https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml

**Comment by adriancole** [comment]
@jcchavezs do you have cycles to fix the publishing?

**Comment by jcchavezs** [comment]
Yes I will check it.

José Carlos Chávez


fre. 27. sep. 2019 kl. 09:09 skrev Adrian Cole <notifications@github.com>:

**Pull request merged**
