### PR TITLE
Fix misspelled word

### PR DESCRIPTION
**Pull request by embs**
occurance -> occurrence

### CODE REVIEW

**Comment by embs** [comment]
While preparing this minor change I couldn't find any information regarding supported Ruby versions. Is this info provided somewhere? If not, shall we do it?

Thanks!

**Comment by adriancole** [comment]
Thanks for the fix!

**Comment by adriancole** [comment]
You mean what version of ruby jekyll needs?

**Comment by embs** [comment]
Yes, @adriancole

**Comment by adriancole** [comment]
done!
https://github.com/openzipkin/openzipkin.github.io/commit/b5ae73915298ce2d95341352bb88b95fb7a4756f

**Pull request merged**
