### PR TITLE
Added dropwizard-zipkin

### PR DESCRIPTION
**Pull request by jplock**

### CODE REVIEW

**Comment by abesto** [comment]
Awesome, thanks!

**Comment by adriancole** [comment]
thanks tons!

since brave supports kafka, does this make dropwizard support it to? or is
there other work to be done?

**Comment by jplock** [comment]
I left that transport out from dropwizard-zipkin as I wasn't sure how popular it was and didn't want to bloat the bundle too much. I should probably find a way to make it extensible so a user could choose to use it.

**Comment by adriancole** [comment]
ahh ok. yeah we are recently, like in last several months, promoting this
more. There's a number of sites that use kafka, though I don't have the
exact count.
http://engineeringblog.yelp.com/2016/04/distributed-tracing-at-yelp.html

That said, http is probably the most accessible, so glad you have it!

**Pull request merged**
